### ISSUE TITLE
v5.1.71-mc1.13.1 won't load

### ISSUE THREAD

**Issue by wrecktify** [NyaaCat/InfernalMobs#14]
Dropped the plugin in and this is the error I get.

[16:17:28] [Server thread/ERROR]: Could not load 'plugins/InfernalMobs-v5.1.71-mc1.13.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NyaaCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:320) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by wrecktify** [comment]
Sorry I didn't know there was a nyaa dependency jar
