### ISSUE TITLE
Exception on cspawn

### ISSUE THREAD

**Issue by FabioZumbi12** [NyaaCat/InfernalMobs#20]
Getting this error when using `/im cspawn command`

IM: InfernalMobs-v5.197
NyaaCore: NyaaCore-v6.3.329-mc1.13.2

Tested with default config and same error: https://gist.github.com/FabioZumbi12/0d272870bb67b723354790838bb2ca5d

```
[00:25:05 INFO]: FabioZumbi12 issued server command: /im cspawn HUSK z12 -120 84 -73
[00:25:05 WARN]: [InfernalMobs] exception during calculating distance
java.lang.NullPointerException: null
        at com.jacob_vejvoda.infernal_mobs.config.LevelConfig.getLevel(LevelConfig.java:41) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.MobManager.getInfernalLevelForLocation(MobManager.java:253) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.CommandHandler.onCommand(CommandHandler.java:293) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[00:25:05 WARN]: [InfernalMobs] exception during reading config for level 1
java.lang.NullPointerException: null
        at com.jacob_vejvoda.infernal_mobs.config.LevelConfig.getLevelConf(LevelConfig.java:144) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.config.LevelConfig.getHealth(LevelConfig.java:75) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.MobManager.setInfernalHealth(MobManager.java:74) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.MobManager.spawnMob(MobManager.java:58) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.MobManager.spawnMob(MobManager.java:43) ~[?:?]
        at com.jacob_vejvoda.infernal_mobs.CommandHandler.onCommand(CommandHandler.java:300) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by phoenixlzx** [comment]
Hello,

Please use the original author's version, this version has been heavily modified and does not use the original configuration.

**Comment by FabioZumbi12** [comment]
I am using a new generated configuration for this version. Upgrading from alpha version from  InfernalMobs-v5.182-alpha.jar build!

**Comment by FabioZumbi12** [comment]
Tested with default config too (added to header) and same error.

**Comment by phoenixlzx** [comment]
Do you have something like the following in your `levels.yml`?

```
level:
  level-1:
    __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig
    level: 1
    attr:
      __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig$Attr
      health: 50
      damage: 3
      damageResist: 0
      exp: 5
      baby: 1.0
    spawn:
      __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig$Range
      from: 100
      to: 3000
      weight: 1
  level-2:
    __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig
    level: 2
    attr:
      __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig$Attr
      health: 100
      damage: 6
      damageResist: 0
      exp: 10
      baby: 1.0
    spawn:
      __class__: com.jacob_vejvoda.infernal_mobs.config.SpawnConfig$Range
      from: 280
      to: 3000
      weight: 2
```

I have to let you know this modified version is not for the public, you can use it though but we may not answer questions in general.

**Comment by FabioZumbi12** [comment]
No, it generated a blank levels.yml file

**Comment by phoenixlzx** [comment]
Then paste the content in it and restart your server.

You can add more level settings using this format.

**Comment by FabioZumbi12** [comment]
Yeah, no errors now!! This levels corresponds to the spawned mob level or with what?

As example with your default config:

```
#  '3': 1
#  '4': 1
#  '5': 1
#  '6': 1
#  '7': 1
```
I need to set levels 3, 4... etc on this file? Why the plugin is looking for level 1?

**Comment by phoenixlzx** [comment]
Because each level has a spawn range, it's calculated from the world's spawn point. You need to modify the `from` and `to` values under `spawn` property.

You can add as many levels as you want just make sure the configuration structure and format is correct. And mobs will spawn as corresponding levels in a specific range.
