### ISSUE TITLE
Error on use latest InfernalMobs 

### ISSUE THREAD

**Issue by FabioZumbi12** [NyaaCat/InfernalMobs#6]
Hi,
The plugin not load because NyaaCore on 1.12.2:

```
[11:23:20 ERROR]: Could not load 'plugins/NyaaCore-v4.0.57-mc1.12.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LangUtils
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [patched_1.12.2.jar:git-Paper-1244]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1244]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:23:20 ERROR]: Could not load 'plugins/InfernalMobs-master-v5.1.22.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NyaaCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [patched_1.12.2.jar:git-Paper-1244]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1244]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by cyilin** [comment]
you need to install LangUtils https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/
